### ISSUE TITLE
Installing / Searching confusion

### ISSUE THREAD

**Issue by Miepee** [karx1/haur#7]
The readme says the following:
---
To install a package:
```bash
haur <package names>
```

To search for a package:
```bash
haur <package names>
```
---

this seems confusing however. If I want to search the AUR for `obs-cli`, how would HAUR know whether to search for obs-cli and report obs-cli + obs-cli-git, or just install obs-cli?

**Comment by karx1** [comment]
Sorry, that's a typo. That should be `haur -s` instead.

**Comment by karx1** [comment]
Fixed in cf37ca9a2739c768a2d342feaaf476a085e38d2b
